-- Generated by tools/catalog/Export-RuntimeCatalog.ps1. Do not edit manually.
local function append(target, source)
	for _, value in source do
		table.insert(target, value)
	end
end

local palettes = {}
append(palettes, require(script.Palettes001))
append(palettes, require(script.Palettes002))
append(palettes, require(script.Palettes003))
append(palettes, require(script.Palettes004))
append(palettes, require(script.Palettes005))
append(palettes, require(script.Palettes006))
append(palettes, require(script.Palettes007))
local outfits = {}
append(outfits, require(script.Outfits001))
append(outfits, require(script.Outfits002))
append(outfits, require(script.Outfits003))
append(outfits, require(script.Outfits004))
append(outfits, require(script.Outfits005))

return {
	version = 1,
	palettes = palettes,
	outfits = outfits,
}
