-- Generated by tools/catalog/Export-RuntimeCatalog.ps1. Do not edit manually.
return {
	{ 7118286254, "+ Casual Doctor Outfit Variant #2", "https://www.roblox.com/catalog/7118286254", "https://tr.rbxcdn.com/180DAY-d6831c88defc878367bd708b6402b98f/420/420/Shirt/Png/noFilter", { { 0x7B7D7D, 152 }, { 0xEEEDED, 41 }, { 0x22252A, 39 } } },
	{ 7118286899, "+ Casual Doctor Outfit Variant #3", "https://www.roblox.com/catalog/7118286899", "https://tr.rbxcdn.com/180DAY-36f5bb3a0a433a79bcb002aea7439b32/420/420/Shirt/Png/noFilter", { { 0x7E8283, 143 }, { 0x485B79, 51 }, { 0xEEEDED, 41 } } },
	{ 6226107703, "+ Open Suit", "https://www.roblox.com/catalog/6226107703", "https://tr.rbxcdn.com/180DAY-e173e01c51b319959a74b6265d8e51d2/420/420/Shirt/Png/noFilter", { { 0x1E1E1E, 204 }, { 0x838380, 34 }, { 0x4E4E4D, 10 } } },
	{ 6070841240, "+ \"Let's Make America Great Again\" Golf Outfit V1", "https://www.roblox.com/catalog/6070841240", "https://tr.rbxcdn.com/180DAY-28b370bbe6bbeb0e78c23f82b98ec77f/420/420/Shirt/Png/noFilter", { { 0x878682, 189 }, { 0xE0E4E5, 41 }, { 0x8B7757, 15 } } },
	{ 7118284871, "+ Casual Doctor Outfit Variant #1", "https://www.roblox.com/catalog/7118284871", "https://tr.rbxcdn.com/180DAY-12435bd935e9f6cef072304feb5587f4/420/420/Shirt/Png/noFilter", { { 0x808181, 132 }, { 0xEEEEEC, 49 }, { 0x22252A, 43 } } },
}
