#requires -Version 5.1
<#
.SYNOPSIS
    Export the analyzed outfit catalog as a compact server-only Luau module.

.DESCRIPTION
    Deduplicates top palettes and emits only fields required by the in-game
    color search. By default merges curated rows from manual-outfits.json
    ahead of analyzed matches.json. Run after Build-Catalog.ps1 and
    Analyze-Colors.ps1.
#>
[CmdletBinding()]
param(
    [string] $InputPath,
    [string] $ManualPath,
    [string] $OutputPath
)

$ErrorActionPreference = 'Stop'

if (-not $InputPath) {
    $InputPath = Join-Path $PSScriptRoot 'output\matches.json'
}
if (-not $ManualPath) {
    $ManualPath = Join-Path $PSScriptRoot 'manual-outfits.json'
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot '..\..\src\server\Data\OutfitCatalog'
}

function ConvertTo-LuauString {
    param([AllowNull()] [string] $Value)

    if ($null -eq $Value) { return '""' }
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    $escaped = $escaped.Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $escaped + '"'
}

function ConvertTo-Rgb24 {
    param([Parameter(Mandatory)] [string] $Hex)

    $value = $Hex.Trim().TrimStart('#')
    if ($value -notmatch '^[0-9A-Fa-f]{6}$') {
        throw "Invalid hex color: $Hex"
    }
    return [Convert]::ToInt32($value, 16)
}

if (-not (Test-Path $InputPath)) {
    throw "Catalog input not found: $InputPath"
}

function Read-OutfitRows {
    param([Parameter(Mandatory)] [string] $Path)

    $parsed = Get-Content -Path $Path -Raw | ConvertFrom-Json
    if ($null -eq $parsed) { return @() }
    if ($parsed -is [System.Array]) { return @($parsed) }
    return @($parsed)
}

# Manual curated outfits are merged first so they win palette metadata on topId conflicts.
$rows = New-Object System.Collections.Generic.List[object]
$manualCount = 0
if (Test-Path $ManualPath) {
    foreach ($row in (Read-OutfitRows -Path $ManualPath)) {
        $rows.Add($row)
        $manualCount += 1
    }
}
foreach ($row in (Read-OutfitRows -Path $InputPath)) {
    $rows.Add($row)
}

$paletteByTop = @{}
$palettes = New-Object System.Collections.Generic.List[object]
$outfits = New-Object System.Collections.Generic.List[object]

foreach ($row in $rows) {
    $colors = @($row.colors | Where-Object { $_.hex -and $null -ne $_.coverage })
    if ($colors.Count -lt 2) { continue }

    $topKey = [string]$row.topId
    if (-not $paletteByTop.ContainsKey($topKey)) {
        $swatches = New-Object System.Collections.Generic.List[object]
        foreach ($color in @($colors | Select-Object -First 3)) {
            $swatches.Add([pscustomobject]@{
                rgb      = ConvertTo-Rgb24 $color.hex
                coverage = [int][Math]::Round([Math]::Max(0.0, [Math]::Min(1.0, [double]$color.coverage)) * 255)
            })
        }

        $palettes.Add([pscustomobject]@{
            topId       = [string]$row.topId
            topName     = [string]$row.topName
            topUrl      = [string]$row.topUrl
            thumbnailUrl = [string]$row.thumbnailUrl
            swatches    = $swatches
        })
        $paletteByTop[$topKey] = $palettes.Count
    }

    $genderCode = switch ([string]$row.gender) {
        'masculine' { 1 }
        'feminine'  { 2 }
        default     { 0 }
    }

    $outfits.Add([pscustomobject]@{
        paletteIndex = [int]$paletteByTop[$topKey]
        bottomId     = [string]$row.bottomId
        bottomName   = [string]$row.bottomName
        bottomUrl    = [string]$row.bottomUrl
        gender       = $genderCode
        priceTotal   = [int]$row.priceTotal
        groupName    = [string]$row.groupName
    })
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-LuauPart {
    param(
        [Parameter(Mandatory)] [string] $Path,
        [Parameter(Mandatory)] [object[]] $Items,
        [Parameter(Mandatory)] [ValidateSet('palette', 'outfit')] [string] $Kind
    )

    $writer = New-Object System.IO.StreamWriter($Path, $false, $utf8NoBom)
    try {
        $writer.WriteLine('-- Generated by tools/catalog/Export-RuntimeCatalog.ps1. Do not edit manually.')
        $writer.WriteLine('return {')
        foreach ($item in $Items) {
            if ($Kind -eq 'palette') {
                $parts = New-Object System.Collections.Generic.List[string]
                foreach ($swatch in $item.swatches) {
                    $parts.Add(('{{ 0x{0:X6}, {1} }}' -f $swatch.rgb, $swatch.coverage))
                }
                $writer.WriteLine(
                    ("`t{{ {0}, {1}, {2}, {3}, {{ {4} }} }}," -f
                        $item.topId,
                        (ConvertTo-LuauString $item.topName),
                        (ConvertTo-LuauString $item.topUrl),
                        (ConvertTo-LuauString $item.thumbnailUrl),
                        ($parts -join ', '))
                )
            } else {
                $writer.WriteLine(
                    ("`t{{ {0}, {1}, {2}, {3}, {4}, {5}, {6} }}," -f
                        $item.paletteIndex,
                        $item.bottomId,
                        (ConvertTo-LuauString $item.bottomName),
                        (ConvertTo-LuauString $item.bottomUrl),
                        $item.gender,
                        $item.priceTotal,
                        (ConvertTo-LuauString $item.groupName))
                )
            }
        }
        $writer.WriteLine('}')
    } finally {
        $writer.Dispose()
    }
}

if (Test-Path $OutputPath -PathType Leaf) {
    Remove-Item -Path $OutputPath -Force
}
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}
Get-ChildItem -Path $OutputPath -Filter '*.lua' -File -ErrorAction SilentlyContinue | Remove-Item -Force

$palettePartNames = New-Object System.Collections.Generic.List[string]
$outfitPartNames = New-Object System.Collections.Generic.List[string]

$paletteChunkSize = 300
for ($start = 0; $start -lt $palettes.Count; $start += $paletteChunkSize) {
    $end = [Math]::Min($start + $paletteChunkSize - 1, $palettes.Count - 1)
    $name = 'Palettes{0:D3}' -f ($palettePartNames.Count + 1)
    Write-LuauPart -Path (Join-Path $OutputPath "$name.lua") -Items @($palettes[$start..$end]) -Kind palette
    $palettePartNames.Add($name)
}

$outfitChunkSize = 500
for ($start = 0; $start -lt $outfits.Count; $start += $outfitChunkSize) {
    $end = [Math]::Min($start + $outfitChunkSize - 1, $outfits.Count - 1)
    $name = 'Outfits{0:D3}' -f ($outfitPartNames.Count + 1)
    Write-LuauPart -Path (Join-Path $OutputPath "$name.lua") -Items @($outfits[$start..$end]) -Kind outfit
    $outfitPartNames.Add($name)
}

$indexWriter = New-Object System.IO.StreamWriter((Join-Path $OutputPath 'init.lua'), $false, $utf8NoBom)
try {
    $indexWriter.WriteLine('-- Generated by tools/catalog/Export-RuntimeCatalog.ps1. Do not edit manually.')
    $indexWriter.WriteLine('local function append(target, source)')
    $indexWriter.WriteLine("`tfor _, value in source do")
    $indexWriter.WriteLine("`t`ttable.insert(target, value)")
    $indexWriter.WriteLine("`tend")
    $indexWriter.WriteLine('end')
    $indexWriter.WriteLine('')
    $indexWriter.WriteLine('local palettes = {}')
    foreach ($name in $palettePartNames) {
        $indexWriter.WriteLine("append(palettes, require(script.$name))")
    }
    $indexWriter.WriteLine('local outfits = {}')
    foreach ($name in $outfitPartNames) {
        $indexWriter.WriteLine("append(outfits, require(script.$name))")
    }
    $indexWriter.WriteLine('')
    $indexWriter.WriteLine('return {')
    $indexWriter.WriteLine("`tversion = 1,")
    $indexWriter.WriteLine("`tpalettes = palettes,")
    $indexWriter.WriteLine("`toutfits = outfits,")
    $indexWriter.WriteLine('}')
} finally {
    $indexWriter.Dispose()
}

Write-Host (
    "Exported {0} palettes ({1} parts) and {2} outfits ({3} parts) to {4} (merged {5} manual outfits from {6})" -f
        $palettes.Count, $palettePartNames.Count, $outfits.Count, $outfitPartNames.Count, $OutputPath, $manualCount, $ManualPath
)
